_jinja_extensions:
  - extensions.py:CurrentYearExtension

project_name:
  type: str
  help: "Project's name:"
  placeholder: MyAwesomeProject
  validator: >-
    {% if not project_name.strip() %}
    ERROR: Must not be empty
    {% endif %}
tmp_project_emoji:
  type: str
  help: "Emoji representing the project (empty for no emoji):"
  default: ""
project_emoji: # Computed to add a space after the emoji if not empty
  type: str
  default: "{{ tmp_project_emoji + ' ' if tmp_project_emoji }}"
  when: false

project_description:
  type: str
  help: "Short and punchy description of the project:"
  placeholder: "{{ project_name }}, the awesome python project that also makes coffee ☕"
project_keywords:
  type: str
  help: "Comma-separated keywords:"
  default: "python,{{ project_name | lower }}"
project_version:
  type: str
  help: "Current version of the project:"
  default: "0.1.0"
  validator: >-
    {% if not (project_version | regex_search('^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$')) %}
    Project version should use Semantic Versioning 2.0.0 (MAJOR.MINOR.PATCH)
    {% endif %}

copyright_license:
  type: str
  help: "Project's license:"
  choices:
    MIT License (MIT):
      value: MIT
    BSD Zero Clause License (0BSD):
      value: 0BSD
    Apache License 2.0 (Apache-2.0):
      value: Apache-2.0
  default: MIT
copyright_year:
  type: str
  help: 'Copyright year or range (e.g. "2022-2023"):'
  default: "{{ CURRENT_YEAR }}"
  validator: >-
    {% if not copyright_year.strip() %}
    ERROR: Must not be empty
    {% endif %}
