_jinja_extensions:
  - extensions.py:CurrentYearExtension

project_name:
  type: str
  help: "Enter the name of the project:"
  placeholder: MyAwesomeProject
  validator: >-
    {% if not project_name.strip() %}
    ERROR: Must not be empty
    {% endif %}

project_description:
  type: str
  help: "Provide a concise description to be used in the Python package overview and the introductory paragraph in the README and documentation's index page:"
  placeholder: "{{ project_name }} is an awesome python project that also makes coffee ☕"
project_keywords:
  type: str
  help: "Provide a list of comma-separated keywords to be using in the Python package overview:"
  default: "python,{{ project_name | lower }}"
project_version:
  type: str
  help: "Enter the current version of the project:"
  default: "0.1.0"
  validator: >-
    {% if not (project_version | regex_search('^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$')) %}
    Project version should use Semantic Versioning 2.0.0 (MAJOR.MINOR.PATCH)
    {% endif %}

copyright_license:
  type: str
  help: "Choose the project's license:"
  choices:
    BSD Zero Clause License (0BSD):
      value: 0BSD
    Apache License 2.0 (Apache-2.0):
      value: Apache-2.0
    MIT License (MIT):
      value: MIT
  default: MIT
copyright_year:
  type: str
  help: 'Enter the copyright year or range (e.g. "2022-2023"):'
  default: "{{ CURRENT_YEAR }}"
  validator: >-
    {% if not copyright_year.strip() %}
    ERROR: Must not be empty
    {% endif %}
